### ISSUE TITLE
What is the speed of running llama 7b on these devices?

### ISSUE THREAD

**Issue by Vandmoon** [nvidia-holoscan/holohub#170]
According to https://www.dfrobot.com/blog-13496.html, the speed is only 1.53 tokens/s when running LLaMA2-7B on NVIDIA Jetson AGX Orin 64GB version. Seems quite slow. Is this the real speed? or it can run much faster with some configurations?

**Comment by NigelNelson** [comment]
I believe that the blog article mistakenly used CPU-only inference. They used the Llama.cpp inference library, which requires special flags at build time and inference time to enable GPU usage, which it appears they didn't do.

Here are some benchmark numbers for IGX (IGX iGPU numbers are identical to AGX benchmarks from my LLM testing)

Models | Prompt | # of parameters | iGPU (Orin) (llama.cpp) | dGPU (Ampere A6000)(llama.cpp) | dGPU (Ada A6000)(llama.cpp) | dGPU(Ampere A6000)(TRT-LLM) | dGPU(Ada A6000)(TRT-LLM)
-- | -- | -- | -- |-- | -- | -- | --
Llama2 | “Once upon a time, “ | 7B 4-bit | 22.5 | 102.8 | 114.1 | 137.56 | 186.583
Llama2 |“Once upon a time, “ | 13B 4-bit | 13.3 | 63.5 | 66.3 | 77.5 | 105.275
Llama2 |“Once upon a time, “ | 70B 4-bit | 3.0 | 14.0 | 16.73 | N/A OOM |  N/A OOM
