### ISSUE TITLE
`volume_rendering_xr`: Magic Leap Headset Disconnects Immediately

### ISSUE THREAD

**Issue by tbirdso** [nvidia-holoscan/holohub#299]
## Overview

A developer reported an issue where their Magic Leap 2 headset disconnected immediately after pairing with the XR Volume Rendering application container host.

## Expected Behavior

Device connects to host container via QR code pairing, and stays connected while `volume_rendering_xr` application runs.

## Observed Behavior

```
ebc@ebc-NVIDIA-IGX-Orin-Development-Kit:/workspace/holohub$ ml_pair.sh
=== Set Up Remote Rendering ===

To pair your Headset and launch Remote Viewer App,
scan the QR code below using the QR Reader APP on your device.

... # QR code is visible

/workspace/holohub$  INFO [LuminRemoteTransport] [PairingHost] Client successfully paired. clientIP="192.168.178.21", clientUUID="542950f9-22fe-77c4-252e-8cd1efc3f872"
 INFO [LuminRemoteTransport] New connection from 192.168.178.21:46286 to 0.0.0.0:50051
 INFO [onClientConnected] Client connected!
 INFO [onMessage] SystemSetup received from client: SessionID=aed7fed3-b90b-4ec4-a1c5-ada4d8e81706
 INFO [handleSystemSetup] Client supports packer encoding mode DEPTH_MONOCHROME_RGB
 INFO [handleSystemSetup] Client supports packer encoding mode DEPTH_ALPHA_YUV
 INFO [handleSystemSetup] Client supports packer encoding mode DEPTH_ALPHAMASK_YUV
 INFO [onClientDisconnected] Client disconnected! # << immediate disconnect
```

## Platform

IGX Development Kit

cc @rbridgewaterML

**Comment by rbridgewaterML** [comment]
Hi Tom, 

Would it be fair to guess that this developer has used our remote rendering in the past? To me this instant disconnect looks like a version mismatch was detected and thus the client hungup. The headset should display a message to this effect (Though in some older builds, we had a bug that disrupted this message)

Getting the newer version of the APK https://thelab.magicleap.cloud/packages_mlhub/artifacts/com.magicleap.remote_render/1.11.64/ml_remote_viewer.apk will resolve it if I am right- if I am incorrect, than notes about what is seen on the headset, and a device bugreport (`adb bugreport`) would both be helpful

**Comment by maximilianofir** [comment]
Hi both, 
Thanks for the help. Indeed, I did not have the APK updated. My bad. The documentation is up to date. 
The connection works well now.

**Comment by tbirdso** [comment]
Closing as resolved. Thanks @rbridgewaterML for your support.
