### ISSUE TITLE
Various SECCOMP Errors When Using "./dev_container build_and_run volume_rendering_xr" Option for Volume Rendering XR

### ISSUE THREAD

**Issue by codenML** [nvidia-holoscan/holohub#377]
When attempting to build and run Volume Rendering XR, there are various SECCOMP errors that cause windrunner-service to crash. These SECCOMP errors are inconsistent. Please see attachment for full logs. In the log, I ran the `./dev_container build_and_run volume_rendering_xr` command from the top level of the repo per the README instructions. Each iteration was different:

1. `ERROR [sigsys_handler] seccomp> Secure computing mode (SECCOMP) violation: 72`
2. `ERROR [sigsys_handler] seccomp> Secure computing mode (SECCOMP) violation: 38`
3. No issue

[seccomp_issues.txt](https://github.com/user-attachments/files/15743952/seccomp_issues.txt)

**Comment by tbirdso** [comment]
Thanks for reporting @codenML . @rbridgewaterML, could you please add these to your update that is underway?

**Comment by coden16** [comment]
I will also note that this does not reproduce when building the container, building the application, and starting `windrunner-service` in the dev container:
`./dev_container build --img holohub:volume_rendering_xr --docker_file ./applications/volume_rendering_xr/Dockerfile # Build the dev container`
`./dev_container launch --img holohub:volume_rendering_xr # Launch the container`
`windrunner-service`

**Comment by tbirdso** [comment]
@codenML can you please confirm that these errors appeared on your IGX devkit (arm64) in dGPU mode?

On review we have also inconsistently encountered 131 (`tgkill`) and 38 (`renameat`) when launching the volume rendering application on IGX dGPU. Let's plan to add those to the Windrunner exemption list.

**Comment by coden16** [comment]
@tbirdso Yes, these errors appeared on my IGX in dGPU mode.
I have also seen 131 in the past although I am not consistently reproducing it.
