### ISSUE TITLE
Getting VK_ERROR_OUT_OF_DEVICE_MEMORY errors when trying to run examples that use Holoviz

### ISSUE THREAD

**Issue by JTMMoo** [nvidia-holoscan/holohub#439]
Hi there,

I am trying to run the example scripts through an AWS EC2 instance. I've followed this tutorial [https://github.com/nvidia-holoscan/holohub/tree/main/tutorials/holoscan-playground-on-aws] and chose NVIDIA GPU-Optimized AMI as suggested. I am also X11 port forwarding using Windows SSH client.

However, when I try to run the example scripts, I'm given these error codes suggesting that there isn't sufficient device memory? 

**From within the holoscan container**
Input:
python3 `/opt/nvidia/holoscan/examples/holoviz/python/holoviz_geometry.py`

Output:
`[info] [fragment.cpp:569] Loading extensions from configs...
[info] [gxf_executor.cpp:249] Creating context
[info] [gxf_executor.cpp:1912] Activating Graph...
[info] [gxf_executor.cpp:1944] Running Graph...
[info] [gxf_executor.cpp:1946] Waiting for completion...
2024-07-23 10:15:53.224 INFO  gxf/std/greedy_scheduler.cpp@191: Scheduling 3 entities
[info] [context.cpp:50] _______________
[info] [context.cpp:50] Vulkan Version:
[info] [context.cpp:50]  - available:  1.3.204
[info] [context.cpp:50]  - requesting: 1.2.0
[info] [context.cpp:50] ______________________
[info] [context.cpp:50] Used Instance Layers :
[info] [context.cpp:50]
[info] [context.cpp:50] Used Instance Extensions :
[info] [context.cpp:50] VK_KHR_surface
[info] [context.cpp:50] VK_KHR_xcb_surface
[info] [context.cpp:50] VK_EXT_debug_utils
[info] [context.cpp:50] VK_KHR_external_memory_capabilities
[info] [context.cpp:50] ____________________
[info] [context.cpp:50] Compatible Devices :
[info] [context.cpp:50] 0: NVIDIA A10G
[info] [context.cpp:50] Physical devices found :
[info] [context.cpp:50] 1
[info] [context.cpp:50] ________________________
[info] [context.cpp:50] Used Device Extensions :
[info] [context.cpp:50] VK_KHR_swapchain
[info] [context.cpp:50] VK_KHR_external_memory
[info] [context.cpp:50] VK_KHR_external_memory_fd
[info] [context.cpp:50] VK_KHR_external_semaphore
[info] [context.cpp:50] VK_KHR_external_semaphore_fd
[info] [context.cpp:50] VK_KHR_push_descriptor
[info] [context.cpp:50] VK_EXT_line_rasterization
[info] [context.cpp:50]
[info] [vulkan_app.cpp:845] Using device 0: NVIDIA A10G (UUID fafb899f6250bdb4d5e5281414a95e48)
[error] [context.cpp:56] /workspace/holoscan-sdk/modules/holoviz/thirdparty/nvpro_core/nvvk/swapchain_vk.cpp(172): Vulkan Error : VK_ERROR_OUT_OF_DEVICE_MEMORY
[error] [context.cpp:56] /workspace/holoscan-sdk/modules/holoviz/thirdparty/nvpro_core/nvvk/swapchain_vk.cpp(172): Vulkan Error : VK_ERROR_OUT_OF_DEVICE_MEMORY
[error] [context.cpp:56] /workspace/holoscan-sdk/modules/holoviz/thirdparty/nvpro_core/nvvk/swapchain_vk.cpp(172): Vulkan Error : VK_ERROR_OUT_OF_DEVICE_MEMORY
[error] [gxf_wrapper.cpp:57] Exception occurred when starting operator: 'holoviz' - Failed to update swap chain.
2024-07-23 10:16:02.610 WARN  gxf/std/entity_executor.cpp@495: Failed to start entity [holoviz]
2024-07-23 10:16:02.610 WARN  gxf/std/greedy_scheduler.cpp@243: Error while executing entity 21 named 'holoviz': GXF_FAILURE
2024-07-23 10:16:02.610 ERROR gxf/std/entity_executor.cpp@586: Entity [holoviz] must be in Started, Tick Pending, Ticking or Idle stage before stopping. Current state is StartPending
2024-07-23 10:16:02.611 INFO  gxf/std/greedy_scheduler.cpp@401: Scheduler finished.
[error] [program.cpp:574] wait failed. Deactivating...
[error] [runtime.cpp:1476] Graph wait failed with error: GXF_FAILURE
[warning] [gxf_executor.cpp:1947] GXF call GxfGraphWait(context) in line 1947 of file /workspace/holoscan-sdk/src/core/executors/gxf/gxf_executor.cpp failed with 'GXF_FAILURE' (1)
[info] [gxf_executor.cpp:1957] Graph execution finished.
[error] [gxf_executor.cpp:1965] Graph execution error: GXF_FAILURE
Traceback (most recent call last):
  File "/opt/nvidia/holoscan/examples/holoviz/python/holoviz_geometry.py", line 326, in <module>
    main(config_count=args.count)
  File "/opt/nvidia/holoscan/examples/holoviz/python/holoviz_geometry.py", line 313, in main
    app.run()
RuntimeError: Failed to update swap chain.
[info] [gxf_executor.cpp:278] Destroying context`

Please let me know if there's something I'm missing here...

**Comment by AndreasHeumann** [comment]
Could you check the NVIDIA driver version? There is a regression with 545 and 550 drivers, might be the same as https://github.com/nvidia-holoscan/holohub/issues/394.

**Comment by JTMMoo** [comment]
Thanks for the quick response, here's what I see when I run `nvidia-smi`:

`Tue Jul 23 12:05:52 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10G                    On  |   00000000:00:1E.0 Off |                    0 |
|  0%   34C    P0             65W /  300W |       0MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+`

**Comment by AndreasHeumann** [comment]
There is a AWS user guide for updating the NVIDIA driver here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html.

**Comment by JTMMoo** [comment]
Updated to 555, but the example script is still not displaying the video unfortunately...Any ideas?

![image](https://github.com/user-attachments/assets/9880f382-c48b-45f3-a32d-29bf8c2f1d88)

**Comment by AndreasHeumann** [comment]
Log file looks good. Do all the examples show this grey screen only?

Could you run `nvidia-smi` to make sure the driver is loaded correctly.

Also could you test a simple Vulkan example like `vkcube` (install `vulkan-tools` package with apt first), Holoviz is using Vulkan.

**Comment by JTMMoo** [comment]
Something odd is happening,`nvidia-smi` is giving different outputs when ran in the ec2 instance and the holoscan container:

![image](https://github.com/user-attachments/assets/c8844c4e-e530-497d-b61b-a14760901388)

vkcube isn't working as you might have expected, the output shows 
`Selected GPU 0: NVIDIA A10G, type: 2` but the window is showing a blank screen.

Running vulkaninfo --summary gives the following, so it's recognising the GPU correctly: 
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.204


Instance Extensions: count = 20
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 4
--------------------------
VK_LAYER_INTEL_nullhw       INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay       Mesa Overlay layer           1.3.211  version 1
VK_LAYER_NV_optimus         NVIDIA Optimus layer         1.3.278  version 1

Devices:
========
GPU0:
        apiVersion         = 4206870 (1.3.278)
        driverVersion      = 2328527232 (0x8aca8180)
        vendorID           = 0x10de
        deviceID           = 0x2237
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = NVIDIA A10G
        driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
        driverName         = NVIDIA
        driverInfo         = 555.42.06
        conformanceVersion = 1.3.8.0
        deviceUUID         = 354d9266-d98d-9f51-bce9-4175da9ad152
        driverUUID         = 173167a4-aa30-5132-a31b-0647ff82d0d4
GPU1:
        apiVersion         = 4206847 (1.3.255)
        driverVersion      = 1 (0x0001)
        vendorID           = 0x10005
        deviceID           = 0x0000
        deviceType         = PHYSICAL_DEVICE_TYPE_CPU
        deviceName         = llvmpipe (LLVM 15.0.7, 256 bits)
        driverID           = DRIVER_ID_MESA_LLVMPIPE
        driverName         = llvmpipe
        driverInfo         = Mesa 23.2.1-1ubuntu3.1~22.04.2 (LLVM 15.0.7)
        conformanceVersion = 1.3.1.1
        deviceUUID         = 6d657361-3233-2e32-2e31-2d3175627500
        driverUUID         = 6c6c766d-7069-7065-5555-494400000000`

**Comment by AndreasHeumann** [comment]
I don't know why you are seeing a grey screen for Vulkan apps with the 555 driver. Could you try the 535 driver?

**Comment by JTMMoo** [comment]
No luck with the 535 driver unfortunately...can't even open a window with vkcube:

![image](https://github.com/user-attachments/assets/6fd0d62c-526f-4343-b52e-871150ac25e8)

Same error when trying to run the video_replayer.py example:

![image](https://github.com/user-attachments/assets/ce712ed4-b7d5-4065-8346-e339a63d1981)

Could it be an issue related to Xming / Xserver on my local Windows PC?

**Comment by rithwikjayanth233** [comment]
Hi @JTMMoo have you found a solution to your issue?
I am running into a similar issue of not being able to display any output when running a holohub application in WSL + Windows 11
