### ISSUE TITLE
How do I run vila_live with VideoStreamReplayerOp instead of V4L2VideoCaptureOp

### ISSUE THREAD

**Issue by Shehjad-Ishan** [nvidia-holoscan/holohub#502]
I tried to run the code with 

```
#videoReplayer
        source =VideoStreamReplayerOp(
            self,
            #directory = "/media/sigmind/URSTP_HDD1414/holohub",
            #basename = "a.webm",
            name= "'source'",
            #allocator=UnboundedAllocator(self, name="pool"),
            **self.kwargs("source"),
        )
       
```

`self.add_flow(source, visualizer, {("output", "receivers")})`

But not working. 

```
[warning] [video_stream_replayer.cpp:136] Could not open index file: /workspace/holohub/b.mp4.gxf_index
[error] [gxf_executor.cpp:1399] Exception occurred during initialization of operator: ''source'' - File open failed with code: 1
Traceback (most recent call last):
  File "/workspace/holohub/applications/vila_live/vila_live.py", line 242, in <module>
    main()
  File "/workspace/holohub/applications/vila_live/vila_live.py", line 238, in main
    app.run()
RuntimeError: File open failed with code: 1
[error] [video_stream_replayer.cpp:175] Failed to close index_file_stream_ with code: 1
```

**Comment by tbirdso** [comment]
Hi @Shehjad-Ishan , you can provide MP4 input to the `vila_live` application via V4L2 loopback (see [discussion](https://github.com/nvidia-holoscan/holohub/pull/489#issuecomment-2327499773)).

@NigelNelson @maximilianofir could you please provide README instructions or a reference for how to set up loopback replay?

**Comment by Shehjad-Ishan** [comment]
> Hi @Shehjad-Ishan , you can provide MP4 input to the `vila_live` application via V4L2 loopback (see [discussion](https://github.com/nvidia-holoscan/holohub/pull/489#issuecomment-2327499773)).
> 
> @NigelNelson @maximilianofir could you please provide README instructions or a reference for how to set up loopback replay?

I have successfully played the video with loopback. What I am looking for is to insert the video file directly into the pipeline.

**Comment by tbirdso** [comment]
> What I am looking for is to insert the video file directly into the pipeline.

After discussion with @NigelNelson we've determined this feature is not currently planned. We recommend continuing to use V4L2 loopback for video input. You can also reference @maximilianofir 's [vila_live replayer PR](https://github.com/nvidia-holoscan/holohub/pull/489) as a baseline for local development.
