### ISSUE TITLE
Question regarding a compatible robotic manipulator

### ISSUE THREAD

**Issue by vikashg** [nvidia-holoscan/holohub#549]
Hello everyone, 
I would like to try a project where a robotic manipulator performs an action based on vision based inputs. I was wondering which robotic manipulators should be compatible with the clara holoscan. Do I need to have a NVIDIA ORIN to implement my application on holoscan. 
Can I get something with an Arduino Calculator?
 
https://www.amazon.com/LewanSoul-Programmable-Feedback-Parameter-Programming/dp/B0793PFGCY?th=1

Any advice will be great. 
Thanks
Vikash

**Comment by NigelNelson** [comment]
Hey Vikash,
A great starting point would be the [Jetson AI Lab LeRobot tutorial](https://www.jetson-ai-lab.com/lerobot.html). For Holoscan SDK compatibility, NVIDIA Orin devices will work as well as x86 machines with an NVIDIA dGPU.
