### ISSUE TITLE
Can application vila_live be run with multiple camera stream?

### ISSUE THREAD

**Issue by Shehjad-Ishan** [nvidia-holoscan/holohub#603]
I need to run inferences on multiple camera feeds. With the present pipeline can it be done?

**Comment by Shehjad-Ishan** [comment]
Hello @NigelNelson. Can you please check out the output?

**Comment by Shehjad-Ishan** [comment]
I was able to integrate multiple sources.

**Comment by NigelNelson** [comment]
@Shehjad-Ishan Apologies for the delayed response, glad you were able to solve this! Also, if you have the time it would be great to see this in an MR, I'm sure others will find this useful.

**Comment by Shehjad-Ishan** [comment]
> @Shehjad-Ishan Apologies for the delayed response, glad you were able to solve this! Also, if you have the time it would be great to see this in an MR, I'm sure others will find this useful.

Sure. I will send a MR request.

**Comment by Shehjad-Ishan** [comment]
> > @Shehjad-Ishan Apologies for the delayed response, glad you were able to solve this! Also, if you have the time it would be great to see this in an MR, I'm sure others will find this useful.
> 
> Sure. I will send a MR request.
@NigelNelson  I have sent MR request for vila_live.py and vila_live.yaml. HTML and websocket.js I have modified to meet my requirements. Should I send a pull request for them too?

**Comment by NigelNelson** [comment]
Awesome @Shehjad-Ishan , yes any related changes necessary for the multi-stream should be in #622
